#!/bin/sh

export VST_PATH="$HOME/VST"
#export XTERM='gnome-terminal -e'
#export XTERM='xterm -e'
export XTERM='screen -T xterm-color -Dm'
#export PATH="/home/xj/Muzyka/fsthost/trunk:/home/xj/Muzyka/fhctrl:$PATH"
#export PATH="/home/studio/SVN/fhctrl:/media/bigpig/secure/XJ/lvst/fsthost/trunk:$PATH"
export FSTHOST_NOGUI=1

MODE=$1
SES_PATH=$2

usage() {
	echo "Usage: $0 load|save SessionPath"
	exit 1
}

start_jack() {
	if ps -eo comm|grep -Fq 'jackd'; then
		echo 'Jack Running'
	else
		if [ ! -r $HOME/.jackdrc ]; then
			echo "No file $HOME/.jackdrc"
			return 1
		fi
		(nohup sh -c ". $HOME/.jackdrc" >/tmp/jackd.$LOGNAME.log 2>&1 &)
		sleep 3
	fi	
}

start_ses() {
	SES_SCRIPT=${SES_PATH%/}/session.sh

	if [ ! -r $SES_SCRIPT ]; then
		echo "No file $SES_SCRIPT"
		return 1
	fi
	. $SES_SCRIPT
}

[ -z "$MODE" -o -z "$SES_PATH" ] && usage

if [ ! -d "$SES_PATH" ] && ! mkdir "$SES_PATH"; then
	echo "Session Directory does not exists, and can't create it $SES"
	exit 1
fi

case $MODE in
	'load')
		start_jack || exit 1
		start_ses || exit 2
		jobs -l
		wait
		;;
	'save')
		fhctrl_sn save $SES_PATH > $SES_PATH/session.sh
		echo 'Session Saved'
		;;
	*) usage
esac
